### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by vitaware** [cocoakekeyu/markdown-img-paste#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [markdown-img-paste](https://github.com/cocoakekeyu/markdown-img-paste) package 0.3.8

### Stack Trace

Uncaught SyntaxError: Unexpected token < in JSON at position 0

```
At file:///C:/Users/tom/AppData/Local/atom/app-1.16.0/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (/packages/markdown-img-paste/lib/markdown-img-paste.coffee:70:33)
    at Request.self.callback (/packages/markdown-img-paste/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/markdown-img-paste/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/markdown-img-paste/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -9:31.3.0 core:paste (input.hidden-input)
     -9:21.7.0 core:save (div.package-detail.panels-item)
     -9:08.2.0 markdown-img-paste:paste (input.hidden-input)
     -8:50.7.0 markdown-preview-enhanced:toggle (input.hidden-input)
  2x -8:10.4.0 vim-mode-plus:delete (input.hidden-input)
  4x -8:09.1.0 vim-mode-plus:move-up (input.hidden-input)
     -5:47.2.0 markdown-img-paste:paste (input.hidden-input)
```

### Non-Core Packages

```
git-plus 7.8.0 
language-gfm-enhanced 0.92.0 
language-markdown 0.22.0 
markdown-img-paste 0.3.8 
markdown-preview-enhanced 0.12.3 
markdown-table-editor 0.5.1 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
markdown-writer 2.6.5 
pdf-view 0.58.0 
script 3.14.1 
tool-bar 1.1.0 
tool-bar-markdown-writer 0.2.0 
vim-mode-plus 0.92.1 
```

**Comment by cocoakekeyu** [comment]
sm.ms的上传接口出问题了，一会再看下

**Comment by vitaware** [comment]
费心了，谢谢！

**Comment by cocoakekeyu** [comment]
发了新版，已经解决

**Comment by GeneralLi95** [comment]
有的时候是因为图片大小超过5MB了，sm.ms只支持5MB以内的图片
