### ISSUE TITLE
Uncaught Error: EACCES: permission denied, mkdir 'assets/'

### ISSUE THREAD

**Issue by dkn22** [cocoakekeyu/markdown-img-paste#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [markdown-img-paste](https://github.com/cocoakekeyu/markdown-img-paste) package 0.3.8

### Stack Trace

Uncaught Error: EACCES: permission denied, mkdir 'assets/'

```
At fs.js:922

Error: EACCES: permission denied, mkdir 'assets/'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.paste (/packages/markdown-img-paste/lib/markdown-img-paste.coffee:49:16)
    at /packages/markdown-img-paste/lib/markdown-img-paste.coffee:13:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1286:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
 11x -0:24 core:paste (input.hidden-input)
     -0:08.4.0 markdown-img-paste:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.7.9 
busy-signal 1.4.1 
intentions 1.1.2 
kite 0.23.0 
language-latex 1.0.0 
latex 0.43.0 
latex-completions 0.3.2 
latex-friend 0.0.11 
latexer 0.3.0 
linter 2.1.4 
linter-spell 0.13.2 
linter-spell-latex 0.9.2 
linter-ui-default 1.2.4 
markdown-image-helper 1.0.4 
markdown-img-paste 0.3.8 
markdown-writer 2.6.5 
```

**Comment by cocoakekeyu** [comment]
设置了选项保存图片在当前目录下的assets目录， 但程序没有权限新建文件夹。

一般是当前编辑的文件没有保存，你试着保存到一个你自己的目录

**Comment by cocoakekeyu** [comment]
this is short translation:
    try save the markdown file firstly
