### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by TangBingqian** [cocoakekeyu/markdown-img-paste#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [markdown-img-paste](https://github.com/cocoakekeyu/markdown-img-paste) package 0.3.11

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///C:/Users/ice/AppData/Local/atom/app-1.37.0/resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/packages/markdown-img-paste/lib/markdown-img-paste.coffee:73:33)
    at Request.self.callback (/packages/markdown-img-paste/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at /packages/markdown-img-paste/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at /packages/markdown-img-paste/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -0:16.7.0 editor:newline (input.hidden-input)
     -0:16.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:16.1.0 snippets:expand (input.hidden-input)
     -0:16.1.0 editor:indent (input.hidden-input)
  2x -0:14.2.0 core:backspace (input.hidden-input)
     -0:13 editor:newline (input.hidden-input)
     -0:12.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:12.2.0 snippets:expand (input.hidden-input)
     -0:12.2.0 editor:indent (input.hidden-input)
     -0:10.7.0 snippets:next-tab-stop (input.hidden-input)
     -0:10.7.0 snippets:expand (input.hidden-input)
     -0:10.7.0 editor:indent (input.hidden-input)
     -0:09.7.0 markdown-img-paste:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
autocomplete-python 1.12.0 
file-icons 2.1.24 
highlight-selected 0.14.0 
insert-timestamp 0.2.4 
markdown-img-paste 0.3.11 
markdown-pdf 2.2.0 
markdown-preview-plus 2.5.8 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
minimap 4.29.9 
```

**Comment by Frozoto1** [comment]
这个可能是图床不可以使用了，或是上传图片到图床遇到了问题，建议将图片保存到本地，可以勾选如下选项，将图片do都保存到本地的assets目录下。

![image](https://user-images.githubusercontent.com/29691488/58449610-7efd5d80-813e-11e9-95a3-526aa237bad8.png)

**Comment by TangBingqian** [comment]
thank you

**Comment by cocoakekeyu** [comment]
这是上传到哪里的报错？
