### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open 'markdown-img-paste-20170304161421978.png'

### ISSUE THREAD

**Issue by wghglory** [cocoakekeyu/markdown-img-paste#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [markdown-img-paste](https://github.com/cocoakekeyu/markdown-img-paste) package 0.3.2

### Stack Trace

Uncaught Error: EACCES: permission denied, open 'markdown-img-paste-20170304161421978.png'

```
At fs.js:640

Error: EACCES: permission denied, open 'markdown-img-paste-20170304161421978.png'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.paste (/packages/markdown-img-paste/lib/markdown-img-paste.coffee:37:12)
    at /packages/markdown-img-paste/lib/markdown-img-paste.coffee:13:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:18.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.theme-one-light-syntax.theme-atom-material-ui)
     -0:13.1.0 grammar-selector:show (atom-text-editor.editor)
     -0:11 core:confirm (input.hidden-input)
     -0:08.3.0 markdown-img-paste:paste (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
aligner 0.22.3 
atom-alignment 0.12.1 
atom-beautify 0.29.17 
atom-css-comb 3.1.0 
atom-html-preview 0.1.22 
atom-live-server 2.1.0 
atom-material-ui 1.3.9 
atom-ternjs 0.17.2 
atom-wrap-in-tag 0.6.0 
autocomplete-paths 1.0.5 
autoprefixer 3.6.1 
block-comment 0.4.3 
color-picker 2.2.5 
compare-files 0.8.0 
convert-to-utf8 0.2.4 
docblockr 0.9.1 
emmet 2.4.3 
file-icons 2.0.15 
fixmyjs 1.4.0 
git-time-machine 1.5.6 
highlight-selected 0.12.0 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
linter 1.11.23 
linter-csslint 1.3.3 
linter-jshint 3.0.2 
linter-markdown 3.1.0 
markdown-image-helper 1.0.4 
markdown-img-paste 0.3.2 
markdown-pdf 1.5.0 
markdown-scroll-sync 2.1.2 
markdown-table-formatter 2.8.4 
markdown-toc 0.4.2 
markdown-writer 2.6.3 
merge-conflicts 1.4.4 
open-in-browsers 0.0.19 
open-terminal-here 2.2.0 
pigments 0.39.0 
script 3.14.1 
Sublime-Style-Column-Selection 1.7.3 
sync-settings 0.8.1 
```

**Comment by cocoakekeyu** [comment]
这可能是这种情况，程序保存截图的文件不能在程序目录创建（没有权限）。可以新建好markdown文件在进行markdown-img-paste操作， 这样图片文件保存在新建的markdown文件目录下。

**Comment by wghglory** [comment]
🙏我确实是在非markdown文件进行了粘贴导致出错。然后我在markdown粘贴，发现了另一个新的错误，请看新的issue
