### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an al...

### ISSUE THREAD

**Issue by wghglory** [cocoakekeyu/markdown-img-paste#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [markdown-img-paste](https://github.com/cocoakekeyu/markdown-img-paste) package 0.3.5

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/derek/.atom/packages/markdown-img-paste/node_modules/sync-request/index.js:10

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at /packages/markdown-img-paste/node_modules/sync-request/index.js:10:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-img-paste/node_modules/qiniu/qiniu/zone.js:1:94)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-img-paste/node_modules/qiniu/qiniu/io.js:11:12)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-img-paste/node_modules/qiniu/index.js:8:7)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.paste (/packages/markdown-img-paste/lib/markdown-img-paste.coffee:97:21)
    at /packages/markdown-img-paste/lib/markdown-img-paste.coffee:13:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:28.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.theme-one-light-syntax.theme-atom-material-ui)
     -0:17.8.0 tree-view:remove (span.name.icon.image-icon.medium-orange)
     -0:09.7.0 markdown-img-paste:paste (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.3.0 
aligner 0.22.3 
atom-alignment 0.12.1 
atom-beautify 0.29.17 
atom-css-comb 3.1.0 
atom-html-preview 0.1.22 
atom-live-server 2.1.2 
atom-material-ui 1.3.9 
atom-ternjs 0.18.2 
atom-wrap-in-tag 0.6.0 
autocomplete-paths 1.0.5 
autoprefixer 3.6.1 
block-comment 0.4.3 
color-picker 2.2.5 
compare-files 0.8.0 
convert-to-utf8 0.2.4 
docblockr 0.9.1 
emmet 2.4.3 
file-icons 2.0.17 
fixmyjs 1.4.1 
git-time-machine 1.5.6 
highlight-selected 0.12.0 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
linter 1.11.23 
linter-csslint 1.3.4 
linter-jshint 3.0.3 
linter-markdown 3.1.0 
markdown-image-helper 1.0.4 
markdown-img-paste 0.3.5 
markdown-pdf 1.5.0 
markdown-scroll-sync 2.1.2 
markdown-table-formatter 2.9.0 
markdown-toc 0.4.2 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
open-in-browsers 0.0.19 
open-terminal-here 2.3.0 
pigments 0.39.0 
script 3.14.1 
Sublime-Style-Column-Selection 1.7.3 
sync-settings 0.8.1 
```

**Comment by ilovin** [comment]
一样的问题，七牛上传不上去

**Comment by evolutionjay** [comment]
一样，七牛传不上去才过来看

**Comment by cocoakekeyu** [comment]
这个跟javascript执行环境有关，应该是使用第三库中某个代码的问题，我会尝试解决的

**Comment by cocoakekeyu** [comment]
问题应该是出在七牛SDK6.1.11版后新使用的sync-request库，我将七牛SDK版本改为6.1.11了，已发布0.3.5版，删除旧版后重新下载即可。

**Comment by wghglory** [comment]
谢谢@cocoakekeyu！最新版0.3.8修复了这个问题。
